# Generated by Django 4.0.4 on 2022-05-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='content',
            field=models.TextField(verbose_name='Содержание поста'),
        ),
    ]
